name:                haskell-lambda
version:             0.1.0
github:              "githubuser/haskell-lambda"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-lambda#readme>

dependencies:
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
- aws-lambda-haskell-runtime >= 4.1.1
- morpheus-graphql    >= 0.19.0
- morpheus-graphql-server >= 0.19.0
#- persistent  >=2.8 && <3.0
#- esqueleto
#- persistent-postgresql >=2.13 && <3.0
#- persistent-template >=2.5 && <3.0
- text >=0.11 && <2.0
- aeson
- bytestring >=  0.10.4 && <0.12
- time
- random  >= 1.1
- transformers
#- fast-logger
- monad-logger
#- monad-metrics
- mtl
- safe-exceptions
- resource-pool
- unliftio-core
- resourcet
- monad-control
- yaml
- rel8
- rio
- cryptonite
- uuid
- memory
- file-embed
- hasql
- hasql-migration
- hasql-pool
- hasql-transaction

library:
  source-dirs: src

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - haskell-lambda

default-extensions:
  - RecordWildCards
#  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
  - NoImplicitPrelude

tests:
  haskell-lambda-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - haskell-lambda
      - base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
      - HUnit
      - hspec
      - tasty
      - morpheus-graphql
      - morpheus-graphql-app
      - morpheus-graphql-code-gen
      - morpheus-graphql-core
      - morpheus-graphql-tests