resolver: lts-23.10

packages:
- .

extra-deps:
  - aws-lambda-haskell-runtime-4.3.2
#  - optparse-applicative-0.17.1.0
#  - ansi-wl-pprint-0.6.9
#  - git: https://github.com/janiez/aws-lambda-haskell-runtime.git
#    commit: 3407003cdedd16a79530e42549c1ee3802c2a918
#  - morpheus-graphql-0.28.0
#  - morpheus-graphql-core-0.28.0
#  - morpheus-graphql-app-0.28.0
#  - morpheus-graphql-code-gen-0.28.0
#  - morpheus-graphql-server-0.28.0
#  - morpheus-graphql-client-0.28.0
#  - morpheus-graphql-subscriptions-0.28.0
#  - morpheus-graphql-code-gen-utils-0.28.0
