resolver: lts-20.6

packages:
- .

extra-deps:
  # - aws-lambda-haskell-runtime-4.1.2
  - git: https://github.com/janiez/aws-lambda-haskell-runtime.git
    commit: 3407003cdedd16a79530e42549c1ee3802c2a918
  - morpheus-graphql-code-gen-0.19.3
  - morpheus-graphql-0.19.3
  - morpheus-graphql-app-0.19.3
  - morpheus-graphql-core-0.19.3
